### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by MarioWork** [AndyOGo/parcel-plugin-inject-style-tag#5]
Is it possible to give a readme file with an example of using this plugin! Thank you for work helping others!

**Comment by AndyOGo** [comment]
Thanks for your question @MarioWork

Parcel V1 plugins just need to be installed, please refer to the docs here for more information on that:
https://v1.parceljs.org/plugins.html#using-plugins

If you have the need to filter specific CSS files, then the readme refers to [`file-path-filter`](https://www.npmjs.com/package/file-path-filter?activeTab=readme#usage)
https://github.com/AndyOGo/parcel-plugin-inject-style-tag/tree/master#configuration

Anyway, as you may know [Parcel V1 is deprecated](https://www.npmjs.com/package/parcel-bundler).

**Comment by MarioWork** [comment]
> @MarioWork 
> Parcel V1 plugins just need to be installed, please refer to the docs here for more information on that:
> https://v1.parceljs.org/plugins.html#using-plugins
> 
> If you have the need to filter specific CSS files, then the readme refers to [`file-path-filter`](https://www.npmjs.com/package/file-path-filter?activeTab=readme#usage)
> https://github.com/AndyOGo/parcel-plugin-inject-style-tag/tree/master#configuration

Oh thank you so much! Does it work with parcel V2? I am having a hard time using inline css with vue and parcel. I am developing a Google apps script addon and does not allow css files ... so yea, your plugin may save my life ahah

**Comment by AndyOGo** [comment]
No, it's a Parcel V1 plugin.

https://github.com/AndyOGo/parcel-plugin-inject-style-tag/blob/6fa0608d1915d924cdb920de91c40c685fcbd8c4/package.json#L39-L41

Anyway Parcel 2 support different methods of inlining, please refer to the docs there.
https://parceljs.org/features/bundle-inlining/
